chore(core): ARC-775 github action to copy readme file to arc-docs
sourcefuse/react-boilerplate-ts-ui pull request #27
Opened 2023-03-23 06:23 UTC by saurabhjindal-SF

2023-03-25 07:17 UTC, mayank0202 requested changes

2023-03-25 07:17 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          API_TOKEN_GITHUB: ${{ secrets.ARC_DOCS_TOKEN }}
`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` It will work

2023-03-25 07:17 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          user_email: 'saurabh.jindal@gmail.com'
Please modify this to use the PR author's info.

2023-03-25 22:03 UTC, mayank0202 approved these changes

2023-03-26 16:49 UTC, jamescrowley321 approved these changes

2023-03-26 16:49 UTC, merged