fix(core): ARC-63 responsive design issue fix
sourcefuse/react-boilerplate-ts-ui pull request #67
Opened 2023-09-11 13:51 UTC by Yogi-Vishwas

Fixed design issues related to responsive design.

https://github.com/sourcefuse/react-boilerplate-ts-ui/assets/107536993/5fd36c60-37d4-447f-893a-0259e66f4c9d
![Screenshot from 2023-09-11 19-38-07](https://github.com/sourcefuse/react-boilerplate-ts-ui/assets/107536993/781edb48-bc18-4e09-9eed-43032c5f46ce)
![Screenshot from 2023-09-11 19-39-07](https://github.com/sourcefuse/react-boilerplate-ts-ui/assets/107536993/c6bd725f-1741-433f-bcd9-e098fc2ce0d6)

![Screenshot from 2023-09-11 19-39-53](https://github.com/sourcefuse/react-boilerplate-ts-ui/assets/107536993/b0c8f7d2-a988-4e2e-9299-6451e3161462)

2023-09-14 05:15 UTC, shubhamp-sf requested changes

2023-09-14 05:15 UTC, shubhamp-sf commented on src/Pages/FormSliderPage.tsx
> +      {!isSmallScreen && <TableOfContent />}
Let's just create a wrapper component that already has this repetitive code on all pages.

2023-09-14 05:15 UTC, shubhamp-sf commented on src/stories/Examples/ResponsiveLoginPage/ResponsiveLoginPage.tsx
> +  };
Is there an alternate of showing values submitted than alerting?
If not let's just toast a success message without this alert.

2023-12-05 10:49 UTC, naveen-sf approved these changes

2023-12-11 12:18 UTC, merged